# Generated by Django 3.2.6 on 2021-08-03 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='created_st',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='update_st',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='pageformat',
            old_name='created_aty',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statusdoc',
            old_name='created_st',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statusdoc',
            old_name='update_st',
            new_name='update_at',
        ),
    ]
