# Generated by Django 3.2.6 on 2021-08-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_control', '0002_auto_20210802_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldproj',
            name='doc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_control.doctype', verbose_name='TIPO DE DOCUMENTO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='doc_type_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_control.pagetype', verbose_name='PADRÃO DE FOLHA'),
        ),
    ]
