# Generated by Django 3.2.6 on 2021-08-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_control', '0003_auto_20210809_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldproj',
            name='doc_type',
        ),
    ]
